require: rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6.9
  NewCops: enable
  Exclude:
    - 'lib/generators/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'vendor/**/*' # added by github actions

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 175

Metrics/MethodLength:
  Max: 15

Naming/AccessorMethodName:
  Exclude:
    - 'lib/memoize_until/store.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/memoize_until/base.rb'
